[workspace]
resolver = "2"

members = ["crates/chronos"]
# Ref: https://www.uffizzi.com/blog/optimizing-rust-builds-for-faster-github-actions-pipelines

[profile.dev]
opt-level = 0
codegen-units = 16

[profile.release]
lto = true
opt-level = 2
codegen-units = 16
